name: workspace
description: A sample command-line application.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.14.0-95.2.beta
workspace:
  - apps/**
  - packages/**

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  

dev_dependencies:
  build: ^4.0.7
  build_runner: ^2.15.1
  build_web_compilers: ^4.8.5
  drift: ^2.34.4 # this is here because devtools_options.yaml has that extension - drift: true
  flutter_lints: 
  kaisel_lint: ^0.5.1
  
# Localization generation is configured by the workspace-level l10n.yaml.
flutter:
  generate: true
