targets:
  $default:
    sources:
      - lib/**
      - pubspec.yaml
      - lib/$lib$
      - $package$

    builders:
      drift_dev:
        options:
          databases:
            default: lib/src/database/drift/app_database.dart

          sql:
            dialect: sqlite
            options:
              version: "3.38"
              modules:
                - fts5