name: infrastructure
description: A sample command-line application.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo
resolution: workspace
environment:
  sdk: ">=3.11.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  drift_flutter: ^0.3.1
  path_provider: ^2.1.6
  

dev_dependencies:
  drift_dev: ^2.34.6
  
