name: l10n
description: A sample command-line application.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

resolution: workspace

environment:
  sdk: ">=3.11.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter

# Don't do this here if you are not exposing or trating that as a standalone stuff
# flutter:
#   generate: true
